backend:
  name: git-gateway
  branch: main

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "productos"
    label: "Productos"
    files:
      - file: "productos.json"
        label: "Lista de productos"
        name: "lista"
        fields:
          - label: "Productos"
            name: "items"
            widget: "list"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - { label: "Imagen", name: "imagen", widget: "image" }