backend:
  name: git-gateway
  branch: main

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "productos"
    label: "Productos"
    files:
      - file: "productos.json"
        label: "Lista de productos"
        name: "lista"
        fields:
          - label: "Productos"
            name: "items"
            widget: "list"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { label: "Precio", name: "precio", widget: "number" }
              - { label: "Descripción", name: "descripcion", widget: "text" }
              - label: "Categoría"
                name: "categoria"
                widget: "select"
                options:
                  - "cpu"
                  - "notebook"
                  - "lote"
                  - "consola"
                  - "placa"
                  - "disco"
                  - "procesador"
                  - "ram"
                  - "retro"
                  - "periferico"
                  - "otros"
              - label: "Imágenes"
                name: "imagenes"
                widget: "list"
                fields:
                  - { label: "Imagen", name: "imagen", widget: "image" }
              - { label: "Link WhatsApp", name: "link", widget: "string" }
              - { label: "Vendido", name: "vendido", widget: "boolean", default: false }