backend:
  name: github
  repo: nahuriverfm/marketplace
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "productos"
    label: "Productos"
    folder: "_productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["cpu","notebook","lote","otros"] }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Link WhatsApp", name: "link", widget: "string" }
